export const MARK_AS_READ = "MARK_AS_READ";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE"
export const ADD_TO_READ_LETTER = "ADD_TO_READ_LETTER"
export const RATE_ARTICLE = "RATE_ARTICLE"
export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMPLAIN = "ADD_COMPLAIN"
